title: "敗犬女主 · 月台"
image: "image.jpg"
source: "https://makeine-anime.com/special/download/"
imageSource: "https://makeine-anime.com/assets/img/special/dl/wp_bgart_01.jpg"
credit: "官方素材"
position: "50% 50%"
mobilePosition: "50% 50%"
