import fs from 'node:fs';
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
pkg.name='roooooxy-blog';pkg.scripts.predev='node scripts/prepare-roxy.mjs';pkg.scripts.prebuild='node scripts/prepare-roxy.mjs';pkg.scripts.build='astro build';pkg.scripts['test:roxy']='node --test tests/roxy.test.mjs';
fs.writeFileSync('package.json',JSON.stringify(pkg,null,2)+'\n');
let config=fs.readFileSync('astro.config.mjs','utf8');
const start=config.indexOf('\t\tswup({');const end=config.indexOf('\n\t\ticon({',start);
if(start!==-1&&end!==-1)config=config.slice(0,start)+config.slice(end);
fs.writeFileSync('astro.config.mjs',config);
let site=fs.readFileSync('src/config/siteConfig.ts','utf8').replace('const SITE_LANG = "en"','const SITE_LANG = "zh_CN"').replace('title: "Mizuki"','title: "Roooooxy’s BLOG"').replace('https://mizuki.mysqil.com/','https://w-joslin-x.github.io/').replace('mode: "custom"','mode: "system"');
fs.writeFileSync('src/config/siteConfig.ts',site);
fs.appendFileSync('.gitignore','\n# Roooooxy generated archives are published alongside the source\n!public/downloads/*.zip\n');
const samples=[
 {slug:'welcome',title:'让记录有一个自己的地方',category:'随笔',tags:['日常','演示'],moods:['🌿 平静'],date:'2026-09-22',description:'从一篇笔记开始，把零散的想法、学习的过程和喜欢的事物，慢慢放进这个小小的角落。',cover:'/images/roxy/makeine-06.jpg',body:'## 从这里开始\n\n这是一篇演示随笔，用来展示博客的卡片、正文和文章之间的关联。你可以把它替换成自己的第一篇文章。\n\n记录不一定要完整。一个刚想明白的问题，一段读书时的感受，或是一张想要留下的照片，都可以是起点。\n\n## 整理，而不是堆积\n\n给文章一个类型，再加几个主题标签，就足够找到它。不必为每一个念头建立复杂的分类体系。\n\n如果想了解这里的写作方式，可以读读 [Markdown 写作清单](/posts/markdown-notes/)。\n\n## 下一页\n\n> 先留下来，再慢慢整理。\n\n这里的内容、格言和歌单都会随着使用逐渐长成自己的样子。'},
 {slug:'markdown-notes',title:'Markdown 写作清单：让笔记保持简单',category:'学习笔记',tags:['Markdown','写作','演示'],moods:['🤔 思考'],date:'2026-09-20',description:'标题、图片、引用和链接：一份可以直接照着用的写作示例，让 Typora 里的笔记自然成为网页。',body:'## 标题与段落\n\n用二级标题组织文章，用三级标题进一步细分。正文不要堆叠太多层级。\n\n### 一个小清单\n\n- 写一个能说明问题的标题。\n- 给出关键背景。\n- 留下思考的过程。\n- 附上参考来源。\n\n## 图片与链接\n\n本地图片放在文章自己的 `images` 目录中，使用相对路径引用。有关下载和附件，见 [图片与附件的整理方式](/posts/images-and-files/)。\n\n## 表格\n\n| 元信息 | 用途 |\n| --- | --- |\n| title | 文章标题 |\n| category | 一个类型 |\n| tags | 多个主题标签 |\n| moods | 可选情绪 |\n\n## 脚注\n\n补充说明可以留在脚注中，而不是打断正文。[^note]\n\n[^note]: 这是脚注的演示内容。\n\n## 回到起点\n\n这篇笔记被 [让记录有一个自己的地方](/posts/welcome/) 引用，页面底部会自动显示反向引用。'},
 {slug:'math-and-code',title:'把公式、代码与流程放进同一篇笔记',category:'学习笔记',tags:['数学','编程','演示'],moods:['🤔 思考','✨ 灵感'],date:'2026-09-18',description:'从一个简单的迭代过程出发，看看数学公式、代码高亮和流程图如何一起解释一个问题。',body:'## 数学表达\n\n梯度下降的一次更新可以写成：\n\n$$\nx_{k+1}=x_k-\\eta\\nabla f(x_k)\n$$\n\n其中 $\\eta$ 是步长。对于 $f(x)=x^2$，梯度为 $2x$。\n\n## 用代码表达\n\n```python\ndef gradient_step(x, learning_rate=0.1):\n    return x - learning_rate * 2 * x\n\nx = 3.0\nfor step in range(10):\n    x = gradient_step(x)\n    print(step, x)\n```\n\n## 过程可视化\n\n```mermaid\nflowchart LR\n    A[设定初值] --> B[计算梯度]\n    B --> C[更新变量]\n    C --> D{是否收敛}\n    D -->|否| B\n    D -->|是| E[输出结果]\n```\n\n## 再想一步\n\n公式解释关系，代码明确步骤，流程图展现结构。三者放在一起，更适合回顾。'},
 {slug:'images-and-files',title:'图片与附件的整理方式',category:'学习笔记',tags:['Markdown','写作','演示'],moods:['🌿 平静'],date:'2026-09-12',description:'一篇文章，一个图片目录。保留相对路径，让网页阅读和离线下载使用同一份内容。',cover:'/images/roxy/makeine-03.jpg',body:'## 一篇文章，一个目录\n\n这篇示例包含一张站主提供的头像图片，用来验证本地图片渲染与 ZIP 下载。\n\n![站主提供的黑白人物头像](./images/avatar.jpg)\n\n## 下载时会发生什么\n\n包含本地图片的文章会自动生成一个 ZIP，里面有 Markdown 原文和图片。打开压缩包中的 Markdown，图片仍然能通过相对路径显示。\n\n## 外部资源\n\n外链图片保留原链接，不会自动下载。其他附件可以放在 GitHub 仓库中，并在文章中添加链接。'},
 {slug:'reading-notes',title:'读完之后，留下一个问题',category:'读书记录',tags:['阅读','演示'],moods:['🤔 思考'],date:'2026-08-28',description:'不必摘抄每一句喜欢的话。也许一个暂时没有答案的问题，更能让一本书留下来。',body:'## 一个问题\n\n这是一篇读书记录的排版示例，并非站主的真实阅读经历。\n\n读书记录可以从三个问题开始：作者在回答什么？我在哪里产生疑问？它与已有经验有什么联系？\n\n## 给未来的自己\n\n不急着写结论。把疑问留在这里，下次回来时，也许会有新的理解。'},
 {slug:'summer',title:'夏天的蓝色，和一些不必急着说的话',category:'随笔',tags:['日常','演示'],moods:['😊 愉快'],date:'2026-08-16',description:'一篇用于展示情绪筛选与独立背景的演示随笔。把生活里的小小片段，留在时间轴上。',cover:'/images/roxy/makeine-04.jpg',background:'/images/roxy/makeine-04.jpg',body:'## 只是一个片段\n\n这是随笔的演示内容。文章可以没有复杂结构，也可以给自己留下一两个小标题。\n\n## 今天的情绪\n\n情绪标签不需要严格分类，只是为这一篇记录留下一点温度。'}
];
for(const p of samples){const dir=`src/content/posts/${p.slug}`;fs.mkdirSync(dir,{recursive:true});const fm={title:p.title,published:p.date,description:p.description,category:p.category,tags:p.tags,moods:p.moods,...(p.cover?{image:p.cover}:{}),...(p.background?{background:p.background,backgroundPosition:'50% 35%'}:{})};const yaml=Object.entries(fm).map(([k,v])=>`${k}: ${JSON.stringify(v)}`).join('\n');fs.writeFileSync(`${dir}/index.md`,`---\n${yaml}\n---\n\n${p.body}\n`)}
fs.mkdirSync('src/content/posts/images-and-files/images',{recursive:true});fs.copyFileSync('public/images/roxy/avatar.jpg','src/content/posts/images-and-files/images/avatar.jpg');
