title: Luv(sic) Grand Finale
artist: Nujabes feat. Shing02
album: Luv(sic) Hexalogy
audio: ''
cover: cover.jpg
source: 'https://open.spotify.com/album/4oT4YRVe43ESrT9rx2LKCM'
coverSource: "https://i.scdn.co/image/ab67616d0000b2731a1ba7785a4b91c8aee7a79c"
